spring:
  application:
    name: medical-records-mainservice
  datasource:
    password: cryptic
    username: root
    url: jdbc:mysql://localhost:3306/smart_health_db #?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  devtools:
    add-properties: false
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
      enabled: true

server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
