server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oAuthDB #?createDatabaseIfNotExist=true
    username: root
    password: cryptic
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        #        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  #dev tools
  devtools:
    add-properties: true
  application:
    name: authorization-service
  transaction:
    default-timeout: 60s

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

check-user-scopes: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka